//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.14 at 02:57:44 PM CET 
//


package be.ipl.projet_ejb.domaine;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import be.ipl.projet_ejb.domaine.Carte;
import be.ipl.projet_ejb.domaine.De;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}de"/>
 *         &lt;element ref="{}carte" maxOccurs="24"/>
 *       &lt;/sequence>
 *       &lt;attribute name="but" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="nbCartesParJoueur" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="nbCartesTotal" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="minJoueurs" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="maxJoueurs" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "de",
    "carte"
})
@XmlRootElement(name = "wazabi")
public class Wazabi {

    @XmlElement(required = true)
    protected De de;
    @XmlElement(required = true)
    protected List<Carte> carte = new ArrayList<Carte>();
    @XmlAttribute(name = "but")
    protected String but;
    @XmlAttribute(name = "nbCartesParJoueur", required = true)
    protected int nbCartesParJoueur;
    @XmlAttribute(name = "nbCartesTotal", required = true)
    protected int nbCartesTotal;
    @XmlAttribute(name = "minJoueurs", required = true)
    protected int minJoueurs;
    @XmlAttribute(name = "maxJoueurs", required = true)
    protected int maxJoueurs;

    /**
     * Gets the value of the de property.
     * 
     * @return
     *     possible object is
     *     {@link De }
     *     
     */
    public De getDe() {
        return de;
    }

    /**
     * Sets the value of the de property.
     * 
     * @param value
     *     allowed object is
     *     {@link De }
     *     
     */
    public void setDe(De value) {
        this.de = value;
    }

    /**
     * Gets the value of the carte property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the carte property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCarte().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Carte }
     * 
     * 
     */
    public List<Carte> getCarte() {
        return this.carte;
    }

    /**
     * Gets the value of the but property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBut() {
        return but;
    }

    /**
     * Sets the value of the but property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBut(String value) {
        this.but = value;
    }

    /**
     * Gets the value of the nbCartesParJoueur property.
     * 
     */
    public int getNbCartesParJoueur() {
        return nbCartesParJoueur;
    }

    /**
     * Sets the value of the nbCartesParJoueur property.
     * 
     */
    public void setNbCartesParJoueur(int value) {
        this.nbCartesParJoueur = value;
    }

    /**
     * Gets the value of the nbCartesTotal property.
     * 
     */
    public int getNbCartesTotal() {
        return nbCartesTotal;
    }

    /**
     * Sets the value of the nbCartesTotal property.
     * 
     */
    public void setNbCartesTotal(int value) {
        this.nbCartesTotal = value;
    }

    /**
     * Gets the value of the minJoueurs property.
     * 
     */
    public int getMinJoueurs() {
        return minJoueurs;
    }

    /**
     * Sets the value of the minJoueurs property.
     * 
     */
    public void setMinJoueurs(int value) {
        this.minJoueurs = value;
    }

    /**
     * Gets the value of the maxJoueurs property.
     * 
     */
    public int getMaxJoueurs() {
        return maxJoueurs;
    }

    /**
     * Sets the value of the maxJoueurs property.
     * 
     */
    public void setMaxJoueurs(int value) {
        this.maxJoueurs = value;
    }

}
